# Generated by Django 4.2.29 on 2026-04-17 23:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataMapping',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('budget_no', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('purchase_order_no', models.CharField(blank=True, max_length=50, null=True)),
                ('settlement_no', models.CharField(blank=True, max_length=50, null=True)),
                ('match_status', models.CharField(choices=[('FULL', '完全匹配'), ('PARTIAL', '部分匹配'), ('NONE', '未匹配')], db_index=True, max_length=10)),
                ('amount_diff', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'data_mappings',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('supplier', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('order_date', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('budget_no', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('mapping_id', models.CharField(blank=True, max_length=36, null=True)),
                ('import_batch_id', models.CharField(max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'purchase_orders',
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('settlement_no', models.CharField(db_index=True, max_length=50, unique=True)),
                ('invoice_no', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('settle_date', models.DateTimeField()),
                ('supplier', models.CharField(max_length=200)),
                ('budget_no', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('mapping_id', models.CharField(blank=True, max_length=36, null=True)),
                ('import_batch_id', models.CharField(max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'settlements',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=200)),
                ('file_size', models.IntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('storage_path', models.CharField(max_length=500)),
                ('uploader_id', models.CharField(db_index=True, max_length=36)),
                ('target_type', models.CharField(blank=True, max_length=20, null=True)),
                ('target_id', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('purchase_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='purchase.purchaserequest')),
            ],
            options={
                'db_table': 'attachments',
            },
        ),
    ]
