# Generated by Django 4.2.29 on 2026-04-17 23:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0001_initial'),
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('template_id', models.CharField(blank=True, max_length=36, null=True)),
                ('target_type', models.CharField(max_length=20)),
                ('current_step', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', '待处理'), ('IN_PROGRESS', '进行中'), ('APPROVED', '已通过'), ('REJECTED', '已驳回'), ('CANCELLED', '已取消')], db_index=True, default='PENDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='budget.budget')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='purchase.purchaserequest')),
            ],
            options={
                'db_table': 'approval_flows',
            },
        ),
        migrations.CreateModel(
            name='WorkflowTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(db_index=True, max_length=30)),
                ('steps', models.JSONField()),
                ('conditions', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'workflow_templates',
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_order', models.IntegerField()),
                ('step_name', models.CharField(max_length=100)),
                ('approver_id', models.CharField(blank=True, max_length=36, null=True)),
                ('approver_role', models.CharField(blank=True, max_length=50, null=True)),
                ('action', models.CharField(blank=True, choices=[('APPROVE', '通过'), ('REJECT', '驳回'), ('WITHDRAW', '撤回')], max_length=10, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('operated_at', models.DateTimeField(blank=True, null=True)),
                ('flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='workflow.approvalflow')),
            ],
            options={
                'db_table': 'approval_steps',
                'ordering': ['step_order'],
            },
        ),
    ]
