# Generated by Django 4.2.29 on 2026-04-17 23:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_no', models.CharField(db_index=True, max_length=20, unique=True)),
                ('applicant_id', models.CharField(max_length=36)),
                ('department_id', models.CharField(max_length=36)),
                ('budget_item_id', models.CharField(blank=True, max_length=36, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('purpose', models.TextField()),
                ('urgency_level', models.CharField(choices=[('LOW', '低'), ('NORMAL', '一般'), ('HIGH', '高'), ('URGENT', '紧急')], default='NORMAL', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PENDING', '待提交'), ('IN_APPROVAL', '审批中'), ('APPROVED', '已通过'), ('REJECTED', '已驳回'), ('CANCELLED', '已取消')], db_index=True, default='DRAFT', max_length=15)),
                ('current_step', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='budget.budget')),
            ],
            options={
                'db_table': 'purchase_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('specification', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('supplier', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase.purchaserequest')),
            ],
            options={
                'db_table': 'purchase_items',
            },
        ),
    ]
