# Generated by Django 4.2.29 on 2026-04-25 13:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=36)),
                ('type', models.CharField(choices=[('APPROVAL_PENDING', '待审批'), ('APPROVAL_RESULT', '审批结果'), ('BUDGET_WARNING', '预算预警'), ('BUDGET_OVERRUN', '预算超支'), ('SYSTEM', '系统通知'), ('REPORT_READY', '报表就绪')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('channels', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
