# Generated by Django 4.2.29 on 2026-04-25 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='模板名称，如：2026年OPEX自编预算模板', max_length=200)),
                ('category', models.CharField(choices=[('OPEX', '运营支出'), ('CAPEX', '资本支出')], help_text='OPEX/CAPEX', max_length=10)),
                ('is_group_allocation', models.BooleanField(default=False, help_text='是否为集团分摊模板')),
                ('year', models.IntegerField(help_text='预算年度')),
                ('version', models.IntegerField(default=1, help_text='模板版本号')),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('ACTIVE', '已启用'), ('ARCHIVED', '已归档')], default='DRAFT', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('task_triggered', models.BooleanField(default=False)),
                ('triggered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'budget_templates',
                'ordering': ['-year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_code', models.CharField(db_index=True, help_text='字段编码，如：budget_no, dept_name', max_length=50)),
                ('field_name', models.CharField(help_text='字段显示名称，如：预算编号', max_length=100)),
                ('field_type', models.CharField(choices=[('TEXT', '文本输入'), ('NUMBER', '数值输入'), ('SELECT', '下拉选择'), ('FORMULA', '公式计算'), ('DATE', '日期选择'), ('MONTH_QTY', '月度数量（1-12月）'), ('MONTH_AMT', '月度金额（1-12月）')], max_length=15)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_editable', models.BooleanField(default=True)),
                ('is_required', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, max_length=500, null=True)),
                ('width', models.CharField(default='120', help_text='列宽，如：120 或 15%', max_length=20)),
                ('formula', models.CharField(blank=True, help_text='公式表达式，如：sum(qty_month_1~12)', max_length=500, null=True)),
                ('is_system', models.BooleanField(default=False)),
                ('is_extension', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='budget_template.budgettemplate')),
            ],
            options={
                'db_table': 'template_fields',
                'ordering': ['sort_order'],
                'unique_together': {('template', 'field_code')},
            },
        ),
        migrations.CreateModel(
            name='TemplateFieldOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option_value', models.CharField(help_text='选项值', max_length=200)),
                ('option_label', models.CharField(help_text='选项显示文本', max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='budget_template.templatefield')),
            ],
            options={
                'db_table': 'template_field_options',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='BudgetTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='PENDING', help_text='PENDING/IN_PROGRESS/SUBMITTED/APPROVED', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_tasks', to='department.department')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='budget_template.budgettemplate')),
            ],
            options={
                'db_table': 'budget_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
