# Generated by Django 4.2.29 on 2026-04-17 23:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('level', models.IntegerField(default=1)),
                ('manager_id', models.CharField(blank=True, max_length=36, null=True)),
                ('budget_admin_id', models.CharField(blank=True, max_length=36, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', '正常'), ('INACTIVE', '停用')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='department.department')),
            ],
            options={
                'db_table': 'departments',
                'ordering': ['sort_order', 'code'],
            },
        ),
    ]
