# Generated by Django 4.2.29 on 2026-04-25 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('dept_type', models.CharField(choices=[('FIRST', '一级部门'), ('SECOND', '二级部门'), ('SS_PUBLIC', 'SS Public')], default='SECOND', max_length=15)),
                ('short_name', models.CharField(blank=True, help_text='一级部门简称，如 SS', max_length=50, null=True)),
                ('level', models.IntegerField(default=2)),
                ('sort_order', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', '正常'), ('INACTIVE', '停用')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='department.department')),
                ('primary_budget_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_budget_departments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'departments',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='DepartmentBudgetAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'department_budget_admins',
                'unique_together': {('department', 'user')},
            },
        ),
        migrations.AddField(
            model_name='department',
            name='secondary_budget_admins',
            field=models.ManyToManyField(blank=True, related_name='secondary_budget_departments', through='department.DepartmentBudgetAdmin', to=settings.AUTH_USER_MODEL),
        ),
    ]
