# Generated by Django 4.2.29 on 2026-04-25 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget_template', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('budget_no', models.CharField(blank=True, db_index=True, help_text='最终预算编号', max_length=50, null=True)),
                ('year', models.IntegerField(db_index=True, help_text='预算年度')),
                ('category', models.CharField(choices=[('OPEX', '运营支出'), ('CAPEX', '资本支出')], help_text='OPEX/CAPEX', max_length=10)),
                ('source', models.CharField(choices=[('SELF_COMPILED', '自编'), ('GROUP_ALLOCATION', '集团分摊'), ('SS_PUBLIC', 'SS Public')], default='SELF_COMPILED', help_text='自编/集团分摊/SS Public', max_length=20)),
                ('version_major', models.IntegerField(default=1, help_text='主版本号（审批通过后+1）')),
                ('version_minor', models.IntegerField(default=0, help_text='次版本号（每次修订+1）')),
                ('version_label', models.CharField(default='v1.0', help_text='版本标签，如 v1.0', max_length=20)),
                ('is_branch', models.BooleanField(default=False)),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PENDING', '待审批'), ('APPROVED', '审批通过'), ('REJECTED', '审批驳回')], db_index=True, default='DRAFT', max_length=15)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='预算总额', max_digits=18)),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, help_text='总数量', max_digits=18)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_budgets', to=settings.AUTH_USER_MODEL)),
                ('branched_from', models.ForeignKey(blank=True, help_text='分支来源版本', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branches', to='budget.budget')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budgets', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='department.department')),
                ('parent_version', models.ForeignKey(blank=True, help_text='父版本', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_versions', to='budget.budget')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_budgets', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_versions', to='budget_template.budgettask')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='budget_template.budgettemplate')),
            ],
            options={
                'db_table': 'budgets',
                'ordering': ['-year', '-version_major', '-version_minor'],
                'unique_together': {('department', 'year', 'category', 'source', 'version_major', 'version_minor')},
            },
        ),
        migrations.CreateModel(
            name='BudgetVersionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(help_text='CREATE/EDIT/SUBMIT/APPROVE/REJECT/BRANCH/MERGE', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('from_version', models.CharField(blank=True, max_length=20, null=True)),
                ('to_version', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_logs', to='budget.budget')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'budget_version_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_no', models.IntegerField(default=0, help_text='条目序号')),
                ('field_data', models.JSONField(default=dict, help_text='动态字段数据，key为field_code')),
                ('computed_fields', models.JSONField(default=dict, help_text='公式计算结果缓存')),
                ('internal_comment', models.TextField(blank=True, help_text='内部管理评论，不带入审批', null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='budget.budget')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_budget_items', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budget_items', to='budget_template.budgettemplate')),
            ],
            options={
                'db_table': 'budget_items',
                'ordering': ['item_no', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetDiff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_count', models.IntegerField(default=0, help_text='新增条目数')),
                ('deleted_count', models.IntegerField(default=0, help_text='删除条目数')),
                ('modified_count', models.IntegerField(default=0, help_text='修改条目数')),
                ('diff_details', models.JSONField(default=dict, help_text='差异详情')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('compared_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compared_diffs', to='budget.budget')),
                ('current_budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_diffs', to='budget.budget')),
            ],
            options={
                'db_table': 'budget_diffs',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(db_index=True, help_text='采购描述/名称', max_length=500)),
                ('specification', models.CharField(blank=True, max_length=500, null=True)),
                ('historical_price', models.DecimalField(decimal_places=2, help_text='历史成交价', max_digits=18)),
                ('suggested_price', models.DecimalField(decimal_places=2, help_text='推荐单价', max_digits=18)),
                ('supplier', models.CharField(blank=True, max_length=200, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(default='MANUAL', max_length=50)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department')),
            ],
            options={
                'db_table': 'purchase_history',
                'ordering': ['-usage_count', '-updated_at'],
                'indexes': [models.Index(fields=['description'], name='purchase_hi_descrip_aa978e_idx'), models.Index(fields=['department', 'description'], name='purchase_hi_departm_804a18_idx')],
            },
        ),
        migrations.CreateModel(
            name='BudgetChangeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operator_role', models.CharField(blank=True, help_text='修改时的角色', max_length=50, null=True)),
                ('change_type', models.CharField(help_text='CREATE/UPDATE/DELETE', max_length=20)),
                ('field_code', models.CharField(blank=True, help_text='修改的字段编码', max_length=50, null=True)),
                ('field_name', models.CharField(blank=True, help_text='修改的字段名称', max_length=100, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, help_text='修改原因，如：统一价格、规范描述、赋予编号', null=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='budget.budget')),
                ('budget_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='change_logs', to='budget.budgetitem')),
                ('operator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'budget_change_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['budget', '-created_at'], name='budget_chan_budget__a3d2d8_idx'), models.Index(fields=['operator', '-created_at'], name='budget_chan_operato_f16580_idx')],
            },
        ),
    ]
