# Generated by Django 4.2.29 on 2026-04-17 23:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('budget_no', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('OPEX', '运营支出'), ('CAPEX', '资本支出')], max_length=5)),
                ('year', models.IntegerField(db_index=True)),
                ('version', models.IntegerField(default=1)),
                ('parent_id', models.CharField(blank=True, max_length=36, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('used_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('frozen_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('payment_entity', models.CharField(blank=True, max_length=200, null=True)),
                ('group', models.CharField(blank=True, max_length=100, null=True)),
                ('account_code', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('DRAFT', '草稿'), ('PENDING', '待审批'), ('APPROVED', '已审批'), ('REJECTED', '已驳回'), ('ADJUSTED', '已调整'), ('CLOSED', '已关闭')], db_index=True, default='DRAFT', max_length=10)),
                ('creator_id', models.CharField(max_length=36)),
                ('remark', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='department.department')),
            ],
            options={
                'db_table': 'budgets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('specification', models.CharField(blank=True, max_length=200, null=True)),
                ('function', models.CharField(blank=True, max_length=200, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('quantity', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('used_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('frozen_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('payment_entity', models.CharField(blank=True, max_length=200, null=True)),
                ('group', models.CharField(blank=True, max_length=100, null=True)),
                ('account_code', models.CharField(blank=True, max_length=50, null=True)),
                ('monthly_plan', models.JSONField(blank=True, null=True)),
                ('project', models.CharField(blank=True, max_length=200, null=True)),
                ('purpose', models.CharField(blank=True, max_length=500, null=True)),
                ('supplier', models.CharField(blank=True, max_length=200, null=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='budget.budget')),
            ],
            options={
                'db_table': 'budget_items',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='BudgetAdjustment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('adjust_no', models.CharField(db_index=True, max_length=20, unique=True)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('adjusted_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('reason', models.TextField()),
                ('items', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', '待审批'), ('APPROVED', '已通过'), ('REJECTED', '已驳回')], default='PENDING', max_length=10)),
                ('creator_id', models.CharField(max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='budget.budget')),
            ],
            options={
                'db_table': 'budget_adjustments',
            },
        ),
    ]
