# Generated by Django 4.2.29 on 2026-04-25 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='模板名称，如：人力外包需求收集表', max_length=200)),
                ('template_type', models.CharField(help_text='模板类型，如：OUTSOURCING/PROCUREMENT/OTHER', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_requirement_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'requirement_templates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequirementTemplateField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_code', models.CharField(help_text='字段编码', max_length=50)),
                ('field_name', models.CharField(help_text='字段显示名称', max_length=100)),
                ('field_type', models.CharField(help_text='TEXT/NUMBER/SELECT/DATE/BOOLEAN', max_length=20)),
                ('is_hidden', models.BooleanField(default=False, help_text='是否为隐藏字段（仅一级预算管理员可见）')),
                ('is_public', models.BooleanField(default=True, help_text='是否对二级部门预算管理员可见')),
                ('is_required', models.BooleanField(default=False)),
                ('default_value', models.CharField(blank=True, max_length=500, null=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='special_requirement.requirementtemplate')),
            ],
            options={
                'db_table': 'requirement_template_fields',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='SpecialRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year', models.IntegerField()),
                ('form_data', models.JSONField(default=dict, help_text='表单填写的数据')),
                ('status', models.CharField(default='DRAFT', help_text='DRAFT/SUBMITTED/APPROVED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_requirements', to='department.department')),
                ('filled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filled_requirements', to=settings.AUTH_USER_MODEL)),
                ('linked_budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='special_requirements', to='budget.budget')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requirements', to='special_requirement.requirementtemplate')),
            ],
            options={
                'db_table': 'special_requirements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequirementTemplateOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('option_value', models.CharField(max_length=200)),
                ('option_label', models.CharField(max_length=200)),
                ('sort_order', models.IntegerField(default=0)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='special_requirement.requirementtemplatefield')),
            ],
            options={
                'db_table': 'requirement_template_options',
                'ordering': ['sort_order'],
            },
        ),
    ]
